#!/usr/bin/env python3

import sys
from TikzBuilder.Builder import Builder

def usage():
    msg = """
tikzbuild imagefile[.json]
"""
    print(msg)
    sys.exit()

try:
    fname = sys.argv[1]
except:
   fname = 'examples/demo.json'

if fname == "--help" or fname == "-h":
    usage()

tb = Builder(fname)
print("TikzBuilder (",tb.version(),")")
tb.run()

